### ISSUE TITLE
P8 Prototyping

### ISSUE THREAD

**Issue by aiceball** [Big-Buddy/Project-Fate-Generator#12]
Pictures of the flow, rough sketch of the software process, Reassign as you see fit

**Comment by felixyf0124** [comment]
[Pd1_#8 Prototyping.docx](https://github.com/Big-Buddy/Project-Fate-Generator/files/520856/Pd1_.8.Prototyping.docx)

**Comment by Big-Buddy** [comment]
[Pd1_.8.Prototyping with BACKEND.docx](https://github.com/Big-Buddy/Project-Fate-Generator/files/522464/Pd1_.8.Prototyping.with.BACKEND.docx)

Added some backend information to the prototype description. Mostly related to the database.
