### ISSUE TITLE
Finding a server to host our project on

### ISSUE THREAD

**Issue by aiceball** [Big-Buddy/Project-Fate-Generator#2]
Either a concordia server, have to figure out whether t supports Node JS, or a private server.

**Comment by Big-Buddy** [comment]
Considering Heroku (free) & OpenShift (30-day trial). Both will have low hardware specs but the ability to handle a lot of traffic isn't really an issue for our purpose (but it might slow down testing in live).
I'll be performing tests this Saturday and maybe Sunday.
HAPPY TURKEY DAY

**Comment by Big-Buddy** [comment]
Heroku is going to be our web server platform, all that remains is configuring a basic DB with the server.
