### ISSUE TITLE
D2 2.1.1. Logical View

### ISSUE THREAD

**Issue by aiceball** [Big-Buddy/Project-Fate-Generator#23]
Basically extended domain model, with the student class as the center of the diagram,and description of what each class is supposed to do. (i.e. student class stores information about the student and the preferences)

**Comment by isisisisisitch** [comment]
![project_classdiagram](https://cloud.githubusercontent.com/assets/22228325/20069252/d66bf952-a4e9-11e6-81b2-7f1584a3ec7e.png)

**Comment by isisisisisitch** [comment]
![project_classdiagram](https://cloud.githubusercontent.com/assets/22228325/20641529/1e63c090-b3c8-11e6-831c-6dc695dddace.png)
