### ISSUE TITLE
D2 3.1.	Detailed Design Diagram

### ISSUE THREAD

**Issue by aiceball** [Big-Buddy/Project-Fate-Generator#27]
Basically a class diagram for every part of the project ( Users, Courses, Schedule, Generator)

**Comment by isisisisisitch** [comment]
![courses subsystem](https://cloud.githubusercontent.com/assets/22228325/20069284/f8be778c-a4e9-11e6-9f8f-0e331a121a67.png)
![schedule subsystem](https://cloud.githubusercontent.com/assets/22228325/20069286/f8c15cae-a4e9-11e6-9c94-ba0a922ac952.png)
![user subsystem](https://cloud.githubusercontent.com/assets/22228325/20069285/f8c07528-a4e9-11e6-8bbc-7a02e874e4a0.png)

**Comment by iAlvisKhoo** [comment]
[3.1 and 3.2 together.docx](https://github.com/Big-Buddy/Project-Fate-Generator/files/576803/3.1.and.3.2.together.docx)

**Comment by isisisisisitch** [comment]
![courses subsystem](https://cloud.githubusercontent.com/assets/22228325/20641565/9c280a18-b3c8-11e6-93ea-6cc6b1fca0ea.png)
![schedule subsystem](https://cloud.githubusercontent.com/assets/22228325/20641567/9c291296-b3c8-11e6-80e0-29384f8cb5aa.png)
![user subsystem](https://cloud.githubusercontent.com/assets/22228325/20641566/9c2900bc-b3c8-11e6-8ca5-cd5f3e3e2c70.png)
