### ISSUE TITLE
Sequence Generator Algorithm

### ISSUE THREAD

**Issue by Big-Buddy** [Big-Buddy/Project-Fate-Generator#32]
Begin rough sketching for the algorithm.
Specify required JSON properties.
Begin coding in JS.

**Comment by pureterror248** [comment]
[Sequence Generator Pseudo Code Algorithm.txt](https://github.com/Big-Buddy/Project-Fate-Generator/files/577401/Sequence.Generator.Pseudo.Code.Algorithm.txt)
