### ISSUE TITLE
D3 1.1.1 Tested Items

### ISSUE THREAD

**Issue by aiceball** [Big-Buddy/Project-Fate-Generator#37]

**Comment by mryanshenghong** [comment]
[Testing login  change account.docx](https://github.com/Big-Buddy/Project-Fate-Generator/files/603876/Testing.login.change.account.docx)

**Comment by claudia-c** [comment]
[2.1 Testing Coverage.docx](https://github.com/Big-Buddy/Project-Fate-Generator/files/604109/2.1.Testing.Coverage.docx)

All the tested items. There are no untested items (1.1.2) at the moment but we can move the items that won't be tested into that part later on.
