### ISSUE TITLE
D3 1.2.4 Security Testing

### ISSUE THREAD

**Issue by aiceball** [Big-Buddy/Project-Fate-Generator#42]

**Comment by Big-Buddy** [comment]
[SQL Injection Attack.docx](https://github.com/Big-Buddy/Project-Fate-Generator/files/605405/SQL.Injection.Attack.docx)

**Comment by Big-Buddy** [comment]
This is just one case for the security testing, I believe Ayan is handling the XSS and MITM cases.

**Comment by Big-Buddy** [comment]
[MITM Attack.docx](https://github.com/Big-Buddy/Project-Fate-Generator/files/607686/MITM.Attack.docx)
